import { getQueryClient } from "@/lib/get-query-client";
import { cn } from "@/lib/utils";
import { QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { Geist, Merriweather } from "next/font/google";
import "./globals.css";
const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-serif",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();
  return (
    <html lang="en" className={cn("font-serif", merriweather.variable)}>
      <body className={`${geistSans.variable} antialiased`}>
        <NextIntlClientProvider>
          <QueryClientProvider client={queryClient}>
            {children}
            <ReactQueryDevtools />
          </QueryClientProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
